ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.5
FROM ${BASE_IMAGE}

LABEL maintainer="AMD Inc"
LABEL OS="registry.access.redhat.com/ubi9/ubi:9.5"

RUN dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y && \
    crb enable && \
    dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --add-repo=https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/ && \
    rpm --import https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official && \
    dnf update -y && \
    dnf install https://repo.radeon.com/amdgpu-install/6.4/rhel/9.5/amdgpu-install-6.4.60400-1.el9.noarch.rpm -y && \
    dnf install rocrand rocm-validation-suite -y && \
    rm -rf /var/cache/yum && \
    rm -rf /var/cache/dnf && \
    dnf clean all

ADD amd-test-runner /amd-test-runner
ADD LICENSE /licenses/LICENSE
RUN chmod +x /amd-test-runner

ENTRYPOINT ["/amd-test-runner"]
